; ButtonBox - ESP32-WROOM-32 + NimBLE HID gamepad genérico
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Fixamos a versão do NimBLE-Arduino porque a API de callbacks do
; BLE Server mudou entre a série 1.x e 2.x. Todo o código deste
; projeto foi escrito contra a API da série 1.4.x.
lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.1

build_flags =
    -D CORE_DEBUG_LEVEL=1
